Gameoflife/Gameoflife/Models/UserTemplate.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameoflife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTemplate
    {
        public int UserTemplateID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string Cells { get; set; }
    
        public virtual User User { get; set; }
    }
}

Gameoflife/Gameoflife/Controllers/UserGamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gameoflife.Models;

namespace Gameoflife.Controllers
{
    public class UserGamesController : Controller
    {
        private GameOfLifeDataEntities1 db = new GameOfLifeDataEntities1();

        // GET: UserGames
        public ActionResult Index()
        {
            var userGames = db.UserGames.Include(u => u.User);
            return View(userGames.ToList());
        }


        public ActionResult CreateActiveGameStep1()
        {

            IEnumerable<SelectListItem> items = db.UserTemplates.Select(c => new SelectListItem
            {
                Value = c.UserTemplateID.ToString(),
                Text = c.Name

            });
            ViewBag.userTemplateID = items;
            return View();
        }

       

        public ActionResult CreateActiveGameStep2(int? userTemplateID)
        {

        
            UserTemplate userTemplate = db.UserTemplates.Find(userTemplateID);
            if (userTemplateID == null)
            {
                return RedirectToAction("CreateActiveGameStep1");
            }
            else
            {
                return View(userTemplate);
            }
        }

        public ActionResult AddGames(int? userTemplateID)
        {

            var activeGames = (List<UserGame>)Session["ActiveGames"];

            UserTemplate userTemplate = db.UserTemplates.Find(userTemplateID);
            UserGame newGame = new UserGame();
  
            newGame.Name = userTemplate.Name;
            newGame.Height = userTemplate.Height;
            newGame.Width = userTemplate.Width;
            newGame.Cells = userTemplate.Cells;
            activeGames.Add(newGame);
            Session["ActiveGames"] = activeGames;
            
            return Redirect("MyActiveGames");
        }


        public ActionResult DeleteActiveGame  (int gameIndex)
        {
             var activeGames = (List<UserGame>)Session["ActiveGames"];
             activeGames.RemoveAt(gameIndex);
             Session["ActiveGames"] = activeGames;
            return Redirect("MyActiveGames");
        }

        public ActionResult SaveActiveGame(int gameIndex)
        {

            var activeGames = (List<UserGame>)Session["ActiveGames"];
            UserGame game2Save = activeGames.ElementAt(gameIndex);
            User sessionUser =(User) Session["User"];
           
            User user=db.Users.FirstOrDefault(u => u.Email == sessionUser.Email);
            game2Save.UserID =(int) user.UserID;
            string name = game2Save.Name;
            var height = game2Save.Height;
            db.UserGames.Add(game2Save);
            db.SaveChanges();
            activeGames.RemoveAt(gameIndex);
            Session["ActiveGames"] = activeGames;
            return Redirect("MySavedGames");
        }

        public ActionResult PlaySavedGame(int gameIndex)
        {

            var activeGames = (List<UserGame>)Session["ActiveGames"];

           
            UserGame userGame= db.UserGames.Find(gameIndex);

            UserGame newGame = new UserGame();

            newGame.Name = userGame.Name;
            newGame.Height = userGame.Height;
            newGame.Width = userGame.Width;
            newGame.Cells = userGame.Cells;
            activeGames.Add(newGame);
            Session["ActiveGames"] = activeGames;

            db.UserGames.Remove(userGame);
            db.SaveChanges();

            return Redirect("MyActiveGames");
        }



        public ActionResult DeleteSavedGame(int gameIndex)
        {
            UserGame userGame = db.UserGames.Find(gameIndex);
            db.UserGames.Remove(userGame);
            db.SaveChanges();
            return Redirect("MySavedGames");
        }

        

        // GET: UserGames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserGame userGame = db.UserGames.Find(id);
            if (userGame == null)
            {
                return HttpNotFound();
            }
            return View(userGame);
        }

        public ActionResult MyActiveGames()
        {
            var activeGames = (List<UserGame>) Session["ActiveGames"];
            return View(activeGames);
        }


        public ActionResult MySavedGames()
        {
            User user = (User)Session["User"];

            if (user == null)
            {
                var userGames = db.UserGames.Include(u => u.User);
                return View(userGames.ToList());
            }
            else
            {
                user = db.Users.Find(user.UserID);

                return View(user.UserGames.ToList());
            }
        }

        // GET: UserGames/Create
        public ActionResult Create()
        {
            //ViewBag.UserTemplates = new SelectList(db.UserTemplates.Select((x=> new { key = x.UserTemplateID, Value = x.Name})));
            var template = new List<SelectListItem>();
            foreach (var x in db.UserTemplates.ToList())
            {
                template.Add(new SelectListItem
                {
                    Text = x.Name,
                    Value = x.UserTemplateID.ToString()
                    
                });
            }

            ViewBag.Templates = template;

            ViewBag.UserID = new SelectList(db.Users, "UserID", "Email");
            return View();
        }

        // POST: UserGames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserGameID,UserID,Name,Height,Width,Cells")] UserGame userGame)
        {
            if (ModelState.IsValid)
            {
                db.UserGames.Add(userGame);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.Users, "UserID", "Email", userGame.UserID);
            return View(userGame);
        }

        // GET: UserGames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserGame userGame = db.UserGames.Find(id);
            if (userGame == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Email", userGame.UserID);
            return View(userGame);
        }

        // POST: UserGames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserGameID,UserID,Name,Height,Width,Cells")] UserGame userGame)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userGame).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Email", userGame.UserID);
            return View(userGame);
        }

        // GET: UserGames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserGame userGame = db.UserGames.Find(id);
            if (userGame == null)
            {
                return HttpNotFound();
            }
            return View(userGame);
        }

        // POST: UserGames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserGame userGame = db.UserGames.Find(id);
            db.UserGames.Remove(userGame);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

  
    }
}

Gameoflife/Gameoflife/Controllers/UserTemplatesController.cs
using System;
using System.Text;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gameoflife.Models;
using Microsoft.Ajax.Utilities;

namespace Gameoflife.Controllers
{
    public class UserTemplatesController : Controller
    {
        private GameOfLifeDataEntities1 db = new GameOfLifeDataEntities1();


        // GET: UserTemplates
        public ActionResult All(string templateTitle, int pageNumber = 1 )
        {

            const int PageSize = 5;

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = PageSize;
            ViewBag.TotalCells = db.UserTemplates.Count();

            if (!string.IsNullOrEmpty(templateTitle))
            {


                /* Select only those templates which contain the name
                 * being searched for.
                templates = templates.Where(t => t.Name.Contains(templateTitle));*/
                return View(db.UserTemplates.OrderBy(u => u.UserID).Where(t => t.Name.Contains(templateTitle)).Skip((pageNumber - 1) * PageSize).Take(PageSize).ToList());
            }

           return
                    View(db.UserTemplates.OrderBy(u => u.UserID).Skip((pageNumber - 1)*PageSize).Take(PageSize).ToList());
          


        }




        // GET: UserTemplates
        public ActionResult Index()
        {

           User user = (User) Session["User"];

            if (user == null)
            {
                var userTemplates = db.UserTemplates.Include(u => u.User);
                return View(userTemplates.ToList());
            }
            else
            {
                user = db.Users.Find(user.UserID);
         
                return View(user.UserTemplates.ToList());
            }
        }


        // GET: UserTemplates/Create
        public ActionResult Create()
        {
           
            return View();
        }

        // POST: UserTemplates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
     
        public ActionResult Create( UserTemplate userTemplate)
        {
            if (ModelState.IsValid)
            {
                User user = (User) Session["User"];
                userTemplate.UserID = user.UserID;

                db.UserTemplates.Add(userTemplate);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View();
        }

       


        // GET: UserTemplates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTemplate userTemplate = db.UserTemplates.Find(id);
            if (userTemplate == null)
            {
                return HttpNotFound();
            }
            return View(userTemplate);
        }

        // POST: UserTemplates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserTemplate userTemplate = db.UserTemplates.Find(id);
            db.UserTemplates.Remove(userTemplate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

      /*  public override string ToString()
        {
            StringBuilder output = new StringBuilder();
            var cells=this.
           /* for (int h = 0; h <= Height - 1; h++)
            {

                for (int w = 0; w <= Width - 1; w++)
                {
                    if (this.Cells[h][w] == Cell.Alive)
                    {
                        output.Append(aliveCellChar); 
                    }
                    else
                    {
                        output.Append(" ");
                    }

                }
                output.AppendLine();
            }


            return output.ToString();
        }*/
    }
}

Gameoflife/Gameoflife/Views/UserTemplates/All.cshtml
@model IEnumerable<Gameoflife.Models.UserTemplate>

@using Gameoflife.Models
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = "All";
}

<h2>All</h2>
@if (Session["User"] != null)
{
    @Html.ActionLink("Create New", "Create")
}
@using (Html.BeginForm("All", "UserTemplates", FormMethod.Get))
{
    <p>
        @*The first paramater needs to match the key used to store the data in the
            the ViewBag.*@
    Search: @Html.TextBox("templateTitle")
        <input type="submit" value="Filter" class="gamebtn" />
    </p>
}

<div class="theGameDisplaywide">
    <table class="table">
        <tr class=""
            h3">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th class="text-center">
                <span>
                    @Html.DisplayNameFor(model => model.Cells)
                </span>
            </th>
            <th>
                Designer
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <span class="h4">
                        @Html.DisplayFor(modelItem => item.Name)
                    </span>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Width)
                </td>
                <td>
                    <pre class="cells"> 
            @Html.DisplayFor(modelItem => item.Cells)</pre>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.FirstName)
                </td>
                <td>
                    @Html.ActionLink("Create Active Game", "CreateActiveGameStep2", "UserGames", new { userTemplateID = item.UserTemplateID }, null)
                </td>
            </tr>
        }

    </table>

</div>

<div class="pagerDiv">

    @{
        int pageNumber = ViewBag.PageNumber;
        int pageSize = ViewBag.PageSize;
        int totalCells = ViewBag.TotalCells;

        IPagedList<UserTemplate> pagedList = new StaticPagedList<UserTemplate>(Model,pageNumber,pageSize,totalCells);

    }
    Page@(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) of @(pagedList.PageCount)
    @Html.PagedListPager(pagedList, page => Url.Action("All", new { pageNumber = page }))




</div>

Gameoflife/Gameoflife/Views/UserTemplates/Create.cshtml
@model Gameoflife.Models.UserTemplateMetadata

@{
    ViewBag.Title = "Create";
}

<script src="~/Scripts/createTemplate.js"></script>



<div id="create">

    <div class="theGame">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4 class= "golbuilder">Game of life builder</h4>

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10" autofocus>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control",id="TemplateName", placeholder = "Enter name", autofocus = "autofocus", required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div id="sizehide">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Height, htmlAttributes: new {@class = "control-label col-md-2"})

                        <div class="col-md-5 createCellSize" id="high">
                            @Html.EditorFor(model => model.Height, new {htmlAttributes = new {@class = "form-control", id = "y", type = "range", min = "1", max = "20"}})

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Width, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-5 createCellSize" id="width">
                            @Html.EditorFor(model => model.Width, new {htmlAttributes = new {@class = "form-control ", id = "x", type = "range", min = "1", max = "20"}})
                        </div>
                    </div>
                </div>
                    <div class="form-group" style="display: none">
                        @Html.LabelFor(model => model.Cells, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cells, new { htmlAttributes = new { @class = "form-control", id = "CellInputDevice" } })
                            @Html.ValidationMessageFor(model => model.Cells, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group" id="hiddenSubmitButton">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Ship Template to the Warehouse" class="btn btn-default gamebtn" id="btn" />
                        </div>
                    </div>

                    <br>
                </div>
        }
        <div>
            <p>
                <button onclick="createblanktemplate()" id="blankTemplate" class="gamebtn">Initialise Template Foundations</button>
                <button onclick="seedCells()" id="seed_Cells" class="gamebtn">Seed Cells</button>
                <button onclick="savetemplatedata()" id="newTemplate" class="gamebtn">Set Template in Stone</button>
            </p>

            <table id="myTable"><!--<tr><span id="cellBuilderHelper">Click on the cells to make them alive</span></tr>--></table>


            <p class="createTemplateInstructions">
                <h4> Instructions:</h4>
                Enter Game Name, Select Height and Width Range <b>MIN</b> 1 <b>Max</b> 20, Initialise Template <br/>
                Click in the black window or seed Cells or do both (green is alive and black is dead) <br/>
                Set the template in stone, And then ship. You can then go and play you new Game.
            </p>

            <br/>
            <hr/>
        </div>
        </div>
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Back to List", "Index")
        </div>
        <div>
        </div>
    </div>
    


      

   

Gameoflife/Gameoflife/Views/UserTemplates/Delete.cshtml
@model Gameoflife.Models.UserTemplate

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserTemplate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cells)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cells)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Gameoflife/Gameoflife/Views/UserTemplates/Index.cshtml
@model IEnumerable<Gameoflife.Models.UserTemplate>



@{
    ViewBag.Title = "My Templates";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="theGameDisplaywide">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cells)
            </th>
            <th>

            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Width)
                </td>
                <td>
                    <pre class="cells"> 
            @Html.DisplayFor(modelItem => item.Cells)
       </pre>
                </td>
                <td>
                    @Html.ActionLink("Create Active Game", "CreateActiveGameStep2", "UserGames", new { userTemplateID = item.UserTemplateID }, null)
                </td>
                @if (Session["User"] != null)
                {

                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.UserTemplateID })
                    </td>
                }
            </tr>
        }

    </table>
</div>

Gameoflife/Gameoflife/Views/UserTemplates/Templates.cshtml
@model IEnumerable<Gameoflife.Models.UserTemplate>

@{
    ViewBag.Title = "All Templates";
}

<h2>All Templates</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Created By
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Width)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cells)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Width)
        </td>
        <td><pre>
            @Html.DisplayFor(modelItem => item.Cells).ToString()
            
            </pre>
        </td>
      
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserTemplateID }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserTemplateID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserTemplateID })
        </td>
    </tr>
}

</table>